networks:
  scooty-web:

services:
    api:
        build:
            dockerfile: Dockerfile
        container_name: "api"
        # networks:
        #   scooty-web:
        ports:
          - 8000:8000
#    server:
#        image: challep/scooty-doo-server:1.0
#        container_name: "server"
#        ports:
#            - "1337:1337"
#        networks:
#            scooty-web:
#        restart:
#            "always"
#        volumes:
#            - ./data:/data
#    bike:
#      image: 
