services:
  db:
    image: postgis/postgis
    container_name: database-db
    networks:
      - scooty-web
    restart: always
    environment:
      POSTGRES_DB: sddb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "sddb", "-h", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    networks:
      - scooty-web
    container_name: database-adminer-1
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - scooty-web
    links:
      - db:db

volumes:
  pgdata:

networks:
  scooty-web:
    driver: bridge
