# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  ruff_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checks with ruff format and ruff check
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Ruff
        run: pip install ruff
      - name: Run ruff format
        run: |
          ruff format
      - name: Run ruff check
        run: |
          ruff check
      
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint with pylint
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Runs pylint
        run: |
          pylint --fail-under=9 .

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Runs pytest
      run: |
        pytest
